version: "3.9"

services:
  jupyterlab:
    image: jupyter/base-notebook:latest
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - /home/codemusic/jupyter_data:/home/jovyan/work
      - /home/codemusic/jupyter_data/jupyter_server_config.json:/home/jovyan/.jupyter/jupyter_server_config.json:ro
    environment:
      - NB_UID=1000
      - NB_GID=100
    healthcheck:
      test: ["CMD-SHELL", "/etc/jupyter/docker_healthcheck.py || exit 1"]
      interval: 5s
      timeout: 3s
      start_period: 5s
      retries: 3
    restart: unless-stopped
