version: '3'

services:
  redmine:
    image: redmine:latest
    restart: always
    ports:
      - "3333:3000"   # Redmine accessible at http://<your-pi-ip>:3333
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: xunjmq84
      REDMINE_DB_DATABASE: redmine
    volumes:
      - redmine_data:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/themes
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: redmine
      MARIADB_USER: redmine
      MARIADB_PASSWORD: xunjmq84
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redmine_data:
  mysql_data:
